name: commitlint (lint commit messages)

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - Check commit messages
        uses: wagoid/commitlint-github-action@v5
